remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: VALUES.MD
description: A structured format for ethical frameworks
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/uprootiny/values.md
